### ISSUE TITLE
1st branch Rseal

### ISSUE THREAD

**Issue by gtarcsay** [gtarcsay/Pipette#1]
Ha Rseal bent van, elcsúszik a feszültségjel

**Comment by ViktorJOlah** [comment]
A seal önmagában arrébb tolja a restinget, mert nonspecifikus leakként fog viselkedni a földelés a végén. Így ha az Rseal közel van a sejthez, akkor nagy lesz a leak, ha viszont szeparálva van egy másik ellenállással (Raccess), akkor kisebb a leak hatása. Érdekes módon a leak miatt megváltozik a bemenő ellenállás is, tehát a soma_v(.5) is msáképp fog kinézni a két variációban. A Command -85 pA-el van lentebb tolva
